
version: '3.8'
services:
  db:
    image: postgis/postgis:latest
    container_name: postgres_db
    ports:
      - '5435:5432'
    environment:
      POSTGRES_DB: taxi24db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root

  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "8080:80"
    depends_on: 
      - db 
    